version: '3.6'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: confluentinc/cp-kafka:5.2.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  elasticsearch:
    container_name: elastic
    image: elasticsearch:7.6.1
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node

  kibana:
    container_name: kibana
    image: kibana:7.6.1
    ports:
      - "5601:5601"
    environment:
      XPACK_MONITORING_ENABLED: "true"
      ELASTICSEARCH_HOSTS: http://elastic:9200

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /postgres/data
    ports:
      - "5432:5432"

  influxdb:
    container_name: influxdb
    image: docker.io/bitnami/influxdb:1-debian-10
    ports:
      - 8086:8086
      - 8088:8088
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
#    volumes:
#      - influxdb-data:/bitnami/influxdb

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  apm:
    image: docker.elastic.co/apm/apm-server:7.9.1
    container_name: apm
    ports:
      - "8200:8200"
      - "14268:14268"
    depends_on:
      - elasticsearch
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elastic:9200"]
        -E apm-server.jaeger.http.enabled=true
        -E apm-server.jaeger.http.host=apm:14268
